<?php
/**
 * Creates config.php (secret key, admin password, protected data folder name).
 *
 *   php make-config.php --site-id=jaipur-dental --notify=owner@example.com
 *   php make-config.php --site-id=x --password="MyStrongPass123" --timezone=Asia/Kolkata
 *   options: --quarantine  --turnstile-site=KEY --turnstile-secret=SECRET --out=/path/config.php --force
 */
if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    exit;
}

$o = getopt('', ['site-id:', 'password:', 'notify:', 'timezone:', 'out:', 'turnstile-site:', 'turnstile-secret:', 'quarantine', 'force']);
$out = $o['out'] ?? (__DIR__ . '/config.php');
if (is_file($out) && !isset($o['force'])) {
    fwrite(STDERR, "config.php already exists. Use --force to overwrite it.\n");
    exit(1);
}

$generated = false;
$password = $o['password'] ?? '';
if ($password === '') {
    $password = rtrim(strtr(base64_encode(random_bytes(12)), '+/', '-_'), '=');
    $generated = true;
}
if (strlen($password) < 8) {
    fwrite(STDERR, "Password must be at least 8 characters.\n");
    exit(1);
}

$siteId = preg_replace('~[^a-z0-9._-]+~i', '-', (string) ($o['site-id'] ?? 'site'));
$ts = isset($o['turnstile-site'], $o['turnstile-secret']);
$dirName = 'sg-data-' . bin2hex(random_bytes(3));
$cfg = [
    'site_id' => $siteId,
    'secret' => bin2hex(random_bytes(32)),
    'data_dir' => '@@DIR@@' . $dirName,   // written as __DIR__ . '/...' below, so the site can be moved to any server
    'timezone' => $o['timezone'] ?? 'Asia/Kolkata',
    'admin_password_hash' => password_hash($password, PASSWORD_DEFAULT),
    'notify_email' => $o['notify'] ?? '',
    'selftest_key' => bin2hex(random_bytes(8)),
    'suspicious_action' => isset($o['quarantine']) ? 'quarantine' : 'allow',
    'turnstile' => ['enabled' => $ts, 'site_key' => $o['turnstile-site'] ?? '', 'secret' => $o['turnstile-secret'] ?? ''],
];

$exported = str_replace("'@@DIR@@" . $dirName . "'", "__DIR__ . '/" . $dirName . "'", var_export($cfg, true));
$php = "<?php\n// Generated by make-config.php. Keep private. Any option from SpamGuard::defaults() can be added here.\nreturn "
    . $exported . ";\n";
if (file_put_contents($out, $php) === false) {
    fwrite(STDERR, "Could not write $out\n");
    exit(1);
}
@chmod($out, 0640);

echo "config.php written: $out\n";
echo "Site ID        : $siteId\n";
echo "Admin page     : /spamguard/spam-admin.php\n";
echo $generated ? "Admin password : $password   (shown only once, save it)\n" : "Admin password : (the one you supplied)\n";
echo "Selftest URL   : /spamguard/selftest.php?key={$cfg['selftest_key']}   (delete selftest.php after setup)\n";
echo "Suspicious mode: {$cfg['suspicious_action']}\n";
