"""Build spamguard/config.php without PHP (port of src/config.js).

data_dir is written as `__DIR__ . '/sg-data-xxxx'`, so it keeps working wherever the site is uploaded.
The admin password hash is PBKDF2-HMAC-SHA256 in the form `pbkdf2$<iterations>$<salt-hex>$<hash-hex>`
(the kit's SpamGuard::verifyPassword() accepts it), because Python's stdlib has no bcrypt.
"""
import hashlib
import os
import re
import secrets

PBKDF2_ITERATIONS = 200000
_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789'
_SITE_ID_JUNK = re.compile(r'[^a-z0-9._-]+', re.I | re.A)


class ConfigError(ValueError):
    """Bad input for the config generator; the message is user-ready."""


class Raw(object):
    """A PHP expression that must be written as code, not as a string."""

    def __init__(self, code):
        self.__raw = code

    @property
    def code(self):
        return self.__raw


def raw(code):
    return Raw(code)


def _php_str(s):
    return "'" + str(s).replace('\\', '\\\\').replace("'", "\\'") + "'"


def php_lit(v, depth=0):
    """Python value -> PHP literal source."""
    if isinstance(v, Raw):
        return v.code
    if v is None:
        return 'null'
    if v is True:
        return 'true'
    if v is False:
        return 'false'
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return str(int(v)) if v == int(v) and abs(v) < 1e21 else repr(v)
    if isinstance(v, str):
        return _php_str(v)
    if isinstance(v, (list, tuple)):
        return '[' + ', '.join(php_lit(x, depth + 1) for x in v) + ']'
    if isinstance(v, dict):
        if not v:
            return '[]'  # (the Node version printed an invalid "[\n,\n]" here)
        pad = '    ' * depth
        lines = ['%s    %s => %s' % (pad, _php_str(k), php_lit(val, depth + 1)) for k, val in v.items()]
        return '[\n' + ',\n'.join(lines) + ',\n' + pad + ']'
    raise TypeError('cannot write %r as a PHP literal' % (type(v),))


def _hex(n):
    return secrets.token_hex(n)


def random_alnum(n):
    """Easy to read out / paste, never starts with a symbol (safe in spreadsheets); uniform choice."""
    return ''.join(secrets.choice(_ALPHABET) for _ in range(n))


def hash_password(password, iterations=PBKDF2_ITERATIONS):
    salt = os.urandom(16)
    h = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt, iterations, 32)
    return 'pbkdf2$%d$%s$%s' % (iterations, salt.hex(), h.hex())


def _len16(s):
    return len(s.encode('utf-16-le', 'surrogatepass')) // 2


def generate_config(o=None, **kw):
    """Contents of spamguard/config.php.

    Options (camelCase keys, like the Node version): password, siteId, timezone, notifyEmail, quarantine,
    turnstile {siteKey, secret}, success {...}, extra {...}.
    Returns {php, password, generatedPassword, selftestKey, dataDirName, siteId}.
    """
    o = dict(o or {})
    o.update(kw)
    generated = not o.get('password')
    password = o.get('password') or random_alnum(16)
    if _len16(password) < 8:
        raise ConfigError('Password kam se kam 8 characters ka hona chahiye')
    site_id = _SITE_ID_JUNK.sub('-', str(o.get('siteId') or 'site'))
    data_dir_name = 'sg-data-' + _hex(3)
    selftest_key = _hex(8)
    cfg = {
        'site_id': site_id,
        'secret': _hex(32),
        'data_dir': raw("__DIR__ . '/%s'" % data_dir_name),
        'timezone': o.get('timezone') or 'Asia/Kolkata',
        'admin_password_hash': hash_password(password),
        'notify_email': o.get('notifyEmail') or '',
        'selftest_key': selftest_key,
        'suspicious_action': 'quarantine' if o.get('quarantine') else 'allow',
    }
    t = o.get('turnstile')
    cfg['turnstile'] = {'enabled': True, 'site_key': t.get('siteKey'), 'secret': t.get('secret')} if t else {'enabled': False, 'site_key': '', 'secret': ''}
    if o.get('success'):
        s = {'redirect': '', 'message': 'Thank you! We have received your enquiry and will contact you soon.', 'json': None}
        s.update(o['success'])
        cfg['success'] = s
    if o.get('extra'):
        cfg.update(o['extra'])
    php = '<?php\n// Generated by SpamGuard Studio. Keep private.\nreturn ' + php_lit(cfg) + ';\n'
    return {'php': php, 'password': password, 'generatedPassword': generated, 'selftestKey': selftest_key, 'dataDirName': data_dir_name, 'siteId': site_id}


def write_config(dest, o=None, **kw):
    """Write config.php to `dest` (refuses to overwrite unless force=True). Returns generate_config()'s dict."""
    o = dict(o or {})
    o.update(kw)
    if os.path.exists(dest) and not o.get('force'):
        raise ConfigError('config.php pehle se hai: %s (--force se badlo)' % dest)
    g = generate_config(o)
    d = os.path.dirname(os.path.abspath(dest))
    os.makedirs(d, exist_ok=True)
    fd = os.open(dest, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o640)
    with os.fdopen(fd, 'w', encoding='utf-8', newline='') as fh:
        fh.write(g['php'])
    return g
