'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const bcrypt = require('bcryptjs');

/** Marker for a PHP expression that must be written as code, not as a string. */
const raw = (code) => ({ __raw: code });

const phpStr = (s) => "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";

function phpLit(v, depth = 0) {
  if (v && typeof v === 'object' && v.__raw) return v.__raw;
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'string') return phpStr(v);
  if (Array.isArray(v)) return '[' + v.map((x) => phpLit(x, depth + 1)).join(', ') + ']';
  const pad = '    '.repeat(depth);
  const lines = Object.entries(v).map(([k, val]) => `${pad}    ${phpStr(k)} => ${phpLit(val, depth + 1)}`);
  return '[\n' + lines.join(',\n') + ',\n' + pad + ']';
}

const hex = (n) => crypto.randomBytes(n).toString('hex');

/** Easy to read out / paste, never starts with a symbol (safe in spreadsheets). Uniform: no modulo bias. */
function randomAlnum(n) {
  const alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789';
  let out = '';
  while (out.length < n) {
    for (const b of crypto.randomBytes(n * 2)) {
      if (b < 256 - (256 % alphabet.length) && out.length < n) out += alphabet[b % alphabet.length];
    }
  }
  return out;
}

/**
 * Build the contents of spamguard/config.php WITHOUT needing PHP (so it works on a Mac without PHP).
 * data_dir is written as `__DIR__ . '/sg-data-xxxx'`, so it keeps working wherever the site is uploaded.
 * The password hash is bcrypt in PHP's `$2y$` form, which PHP's password_verify() accepts.
 */
function generateConfig(o = {}) {
  const generatedPassword = !o.password;
  const password = o.password || randomAlnum(16);
  if (password.length < 8) throw new Error('Password kam se kam 8 characters ka hona chahiye');
  const siteId = String(o.siteId || 'site').replace(/[^a-z0-9._-]+/gi, '-');
  const dataDirName = 'sg-data-' + hex(3);
  const selftestKey = hex(8);
  const hash = bcrypt.hashSync(password, 10).replace(/^\$2[ab]\$/, '$2y$');
  const cfg = {
    site_id: siteId,
    secret: hex(32),
    data_dir: raw(`__DIR__ . '/${dataDirName}'`),
    timezone: o.timezone || 'Asia/Kolkata',
    admin_password_hash: hash,
    notify_email: o.notifyEmail || '',
    selftest_key: selftestKey,
    suspicious_action: o.quarantine ? 'quarantine' : 'allow',
    turnstile: o.turnstile
      ? { enabled: true, site_key: o.turnstile.siteKey, secret: o.turnstile.secret }
      : { enabled: false, site_key: '', secret: '' },
  };
  if (o.success) cfg.success = Object.assign({ redirect: '', message: 'Thank you! We have received your enquiry and will contact you soon.', json: null }, o.success);
  if (o.extra) Object.assign(cfg, o.extra);
  const php = '<?php\n// Generated by SpamGuard Studio. Keep private.\nreturn ' + phpLit(cfg) + ';\n';
  return { php, password, generatedPassword, selftestKey, dataDirName, siteId };
}

function writeConfig(dest, o = {}) {
  if (fs.existsSync(dest) && !o.force) throw new Error('config.php pehle se hai: ' + dest + ' (--force se badlo)');
  const g = generateConfig(o);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, g.php, { mode: 0o640 });
  return g;
}

module.exports = { generateConfig, writeConfig, phpLit, raw };
